# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Just Another PowerShell Blog
tagline:          'Automation is Fun!'
description:      'This is just a place to try and share useful tidbits i learn as i struggle my way through day to day life.'
url:              http://hematic.github.io
baseurl:          /

author:
  name:           'Phillip Marshall'
  linkedin:       https://www.linkedin.com/in/phillipmarshall1/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/hematic/hematic.github.io
